linux:
  script:
    - docker build docker/linux -t persalys/linux
    - docker run --rm --volume `pwd`:/io persalys/linux sh -c "/io/docker/linux/run_docker_build.sh"
  except:
    - tags

mingw:
  script:
    - docker build docker/mingw -t persalys/mingw
    - docker run --rm --volume `pwd`:/io persalys/mingw sh -c "/io/docker/mingw/run_docker_build.sh"
  except:
    - tags

linux-tag:
  script:
    - docker build docker/linux -t persalys/linux
    - docker run --rm --volume `pwd`:/io persalys/linux sh -c "/io/docker/linux/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    name: persalys-appimage
    paths:
      - persalys*.AppImage
    expire_in: 2 yrs
  only:
    - tags

mingw-tag:
  script:
    - docker build docker/mingw -t persalys/mingw
    - docker run --rm --volume `pwd`:/io persalys/mingw sh -c "/io/docker/mingw/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    name: persalys-exe
    paths:
      - persalys*.exe
    expire_in: 2 yrs
  only:
    - tags

