linux:
  script:
    - ./utils/build_locally.sh linux
  except:
    - tags

mingw:
  script:
    - ./utils/build_locally.sh mingw
  except:
    - tags

linux-tag:
  script:
    - ./utils/build_locally.sh linux
  artifacts:
    name: persalys-appimage
    paths:
      - persalys*.AppImage
    expire_in: 2 yrs
  only:
    - tags

mingw-tag:
  script:
    - ./utils/build_locally.sh mingw
  artifacts:
    name: persalys-exe
    paths:
      - persalys*.exe
    expire_in: 2 yrs
  only:
    - tags

