linux:
  script:
    - docker pull persalys/linux:10.0
    - docker run --rm --volume `pwd`:/io persalys/linux:10.0 sh -c "/io/docker/linux/run_docker_build.sh"
  except:
    - tags

mingw:
  script:
    - docker pull persalys/mingw:10.0
    - docker run --rm --volume `pwd`:/io persalys/mingw:10.0 sh -c "/io/docker/mingw/run_docker_build.sh"
  except:
    - tags

linux-tag:
  script:
    - docker pull persalys/linux:10.0
    - docker run --rm --volume `pwd`:/io persalys/linux:10.0 sh -c "/io/docker/linux/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    paths:
      - persalys*.AppImage
  only:
    - tags

mingw-tag:
  script:
    - docker pull persalys/mingw:10.0
    - docker run --rm --volume `pwd`:/io persalys/mingw:10.0 sh -c "/io/docker/mingw/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    paths:
      - persalys*.exe
  only:
    - tags

