linux:
  script:
    - docker pull persalys/linux:18.0
    - docker run --rm --volume `pwd`:/io persalys/linux:18.0 sh -c "/io/docker/linux/run_docker_build.sh"
  except:
    - tags
mingw:
  script:
    - docker pull persalys/mingw:18.0
    - docker run --rm --volume `pwd`:/io persalys/mingw:18.0 sh -c "/io/docker/mingw/run_docker_build.sh"
  except:
    - tags
linux-tag:
  script:
    - docker pull persalys/linux:18.0
    - docker run --rm --volume `pwd`:/io persalys/linux:18.0 sh -c "/io/docker/linux/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    name: persalys-appimage
    paths:
      - persalys*.AppImage
    expire_in: 2 yrs
  only:
    - tags
mingw-tag:
  script:
    - docker pull persalys/mingw:18.0
    - docker run --rm --volume `pwd`:/io persalys/mingw:18.0 sh -c "/io/docker/mingw/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    name: persalys-exe
    paths:
      - persalys*.exe
    expire_in: 2 yrs
  only:
    - tags
