#!/bin/sh

# installs paraview in ./pv-linux-install

set -e

git clone https://gitlab.kitware.com/paraview/paraview.git
cd paraview
git checkout v5.4.1
git submodule init
git submodule update

# qt 5.5 on xenial
sed -i 's|_qt_min_version "5.6"|_qt_min_version "5.5"|g' CMake/ParaViewQt.cmake

mkdir build && cd build

cmake \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DVTK_USE_64BIT_IDS=OFF \
  -DVTK_NO_PYTHON_THREADS=OFF \
  -DVTK_PYTHON_FULL_THREADSAFE=ON \
  -DPARAVIEW_ENABLE_PYTHON=ON \
  -DBUILD_DOCUMENTATION=OFF \
  -DVTK_USE_OGGTHEORA_ENCODER=ON \
  -DVTK_USE_SYSTEM_OGGTHEORA=ON \
  -DVTK_USE_SYSTEM_FREETYPE=ON \
  -DVTK_USE_SYSTEM_GL2PS=OFF \
  -DVTK_USE_SYSTEM_JPEG=ON \
  -DVTK_USE_SYSTEM_NETCDF=ON \
  -DVTK_USE_SYSTEM_GLEW=ON \
  -DVTK_USE_SYSTEM_PNG=ON \
  -DVTK_USE_SYSTEM_TIFF=ON \
  -DVTK_USE_SYSTEM_ZLIB=ON \
  -DVTK_USE_SYSTEM_LIBXML2=ON \
  -DVTK_USE_SYSTEM_EXPAT=ON \
  -DVTK_USE_SYSTEM_HDF5=ON \
  -DPARAVIEW_ENABLE_CATALYST:BOOL=ON \
  -DPARAVIEW_BUILD_QT_GUI:BOOL=ON \
  -DPARAVIEW_QT_VERSION=5 \
  -DVTK_BUILD_QT_DESIGNER_PLUGIN:BOOL=OFF \
  -DPARAVIEW_ENABLE_MATPLOTLIB:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_Moments:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_SierraPlotTools:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_SLACTools:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_AnalyzeNIfTIIO:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_ArrowGlyph:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_CatalystScriptGeneratorPlugin:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_GMVReader:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_MobileRemoteControl:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_NonOrthogonalSource:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_QuadView:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_PacMan:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_PrismPlugin:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_RGBZView:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_SciberQuestToolKit:BOOL=OFF \
  -DPARAVIEW_BUILD_PLUGIN_StreamingParticles:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_UncertaintyRendering:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_EyeDomeLighting:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_ForceTime:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_H5PartReader:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_PointSprite:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_SurfaceLIC:BOOL=ON \
  -DPARAVIEW_BUILD_PLUGIN_CatalystScriptGeneratorPlugin=ON \
  -DCMAKE_INSTALL_RPATH=$PWD/../../pv-linux-install/lib/paraview \
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=OFF  \
  -DCMAKE_SKIP_RPATH=OFF \
  -DVTK_CUSTOM_LIBRARY_SUFFIX="" \
  -DCMAKE_INSTALL_PREFIX=$PWD/../../pv-linux-install \
  -DVTK_INSTALL_LIBRARY_DIR="lib/paraview" \
  -DVTK_INSTALL_ARCHIVE_DIR="lib/paraview" \
  -DVTK_INSTALL_INCLUDE_DIR="include/paraview" \
  -DVTK_INSTALL_DATA_DIR="share/paraview" \
  -DVTK_INSTALL_DOC_DIR="share/doc/paraview" \
  -DVTK_INSTALL_PACKAGE_DIR="lib/cmake/paraview" \
  -DVTK_USE_SYSTEM_PROTOBUF=ON \
  -DPARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON \
  ..
make install -j8
cd ../..
